const mongoose = require('mongoose');
const { normalizeSlug } = require('../utils/bookSlug');

const bookSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, 'Please add a book title'],
      trim: true,
    },
    slug: {
      type: String,
      required: [true, 'Please add a book slug'],
      unique: true,
      trim: true,
      lowercase: true,
    },
    description: {
      type: String,
      required: [true, 'Please add a description'],
    },
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category',
      required: true,
    },
    price: {
      type: Number,
      required: [true, 'Please add a price'],
      min: [0, 'Price must be greater than or equal to 0'],
    },
    mrp: {
      type: Number,
      required: [true, 'Please add an MRP'],
      min: [0, 'MRP must be greater than or equal to 0'],
    },
    royaltyPercentage: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },
    coverImage: {
      type: String,
      default: '',
    },
    stock: {
      type: Number,
      default: 0,
    },
    reservedStock: {
      type: Number,
      default: 0,
      min: 0,
    },
    ratings: {
      type: Number,
      default: 0,
    },
    reviewCount: {
      type: Number,
      default: 0,
    },
    status: {
      type: String,
      enum: ['draft', 'published', 'archived'],
      default: 'draft',
    },
    discountPrice: {
      type: Number,
    },
    isBestseller: {
      type: Boolean,
      default: false,
    },
    isFeatured: {
      type: Boolean,
      default: false,
    },
    isNewRelease: {
      type: Boolean,
      default: false,
    },
    isbn: {
      type: String,
    },
    pages: {
      type: Number,
    },
    format: {
      type: String,
      enum: ['hardcover', 'paperback', 'ebook', 'audiobook'],
      default: 'paperback',
    },
  },
  {
    timestamps: true,
  }
);

// Create a text index for search
bookSchema.index({ title: 'text', description: 'text' });

const hasValue = (value) => value !== undefined && value !== null;

const normalizeCommercialPrice = (target) => {
  const hasMrp = hasValue(target.mrp);
  const hasPrice = hasValue(target.price);

  if (hasMrp && hasPrice && Number(target.mrp) !== Number(target.price)) {
    return false;
  }

  if (hasMrp && !hasPrice) {
    target.price = target.mrp;
  }

  if (!hasMrp && hasPrice) {
    target.mrp = target.price;
  }

  return true;
};

bookSchema.pre('validate', function normalizeMrpCompatibility() {
  if (this.slug !== undefined && this.slug !== null) {
    this.slug = normalizeSlug(this.slug);
  }

  if (!this.slug) {
    this.invalidate('slug', 'Book slug is required and must be generated by the service layer');
  }

  if (!normalizeCommercialPrice(this)) {
    this.invalidate('mrp', 'MRP and legacy price must match during price compatibility migration');
  }
});

bookSchema.pre(['findOneAndUpdate', 'updateOne', 'updateMany'], function normalizeMrpUpdateCompatibility() {
  const update = this.getUpdate() || {};
  const direct = { ...update };
  const set = { ...(update.$set || {}) };
  const mrp = hasValue(set.mrp) ? set.mrp : direct.mrp;
  const price = hasValue(set.price) ? set.price : direct.price;

  if (hasValue(mrp) && hasValue(price) && Number(mrp) !== Number(price)) {
    throw new Error('MRP and legacy price must match during price compatibility migration');
  }

  if (hasValue(mrp) || hasValue(price)) {
    const val = hasValue(mrp) ? mrp : price;
    set.mrp = val;
    set.price = val;
    delete direct.mrp;
    delete direct.price;
  }

  this.setUpdate({
    ...direct,
    ...(Object.keys(set).length > 0 && { $set: set })
  });
});

module.exports = mongoose.model('Book', bookSchema);
